ALTER TABLE players
    ALTER COLUMN baseprice TYPE DOUBLE PRECISION USING baseprice::DOUBLE PRECISION,
    ALTER COLUMN baseprice SET DEFAULT 0.0,
    ALTER COLUMN baseprice SET NOT NULL;

ALTER TABLE players
    ALTER COLUMN sellprice TYPE DOUBLE PRECISION USING sellprice::DOUBLE PRECISION,
    ALTER COLUMN sellprice SET DEFAULT 0.0;